// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cart_items.sql

package db

import (
	"context"
	"time"
)

const createCartItems = `-- name: CreateCartItems :exec
INSERT INTO cart_items (id, cart_id, product_id, quantity, created_at)
VALUES (
  unnest($1::text[]),
  $2::text,
  unnest($3::text[]),
  unnest($4::int[]),
  unnest($5::timestamptz[])
)
`

type CreateCartItemsParams struct {
	Ids        []string
	CartID     string
	ProductIds []string
	Quantities []int
	CreatedAts []time.Time
}

func (q *Queries) CreateCartItems(ctx context.Context, arg CreateCartItemsParams) error {
	_, err := q.db.Exec(ctx, createCartItems,
		arg.Ids,
		arg.CartID,
		arg.ProductIds,
		arg.Quantities,
		arg.CreatedAts,
	)
	return err
}

const deleteCartItemsByCartId = `-- name: DeleteCartItemsByCartId :exec
DELETE FROM cart_items
WHERE cart_id = $1::text
`

func (q *Queries) DeleteCartItemsByCartId(ctx context.Context, cartID string) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByCartId, cartID)
	return err
}
