// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: carts.sql

package db

import (
	"context"
	"time"
)

const createCart = `-- name: CreateCart :exec
INSERT INTO carts (
  id, created_at, updated_at
) VALUES ($1, $2, $3)
`

type CreateCartParams struct {
	CartID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) error {
	_, err := q.db.Exec(ctx, createCart, arg.CartID, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const deleteCartById = `-- name: DeleteCartById :exec
DELETE FROM carts
WHERE id = $1::text
`

func (q *Queries) DeleteCartById(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCartById, id)
	return err
}

const getCartByIdWithItems = `-- name: GetCartByIdWithItems :one
SELECT
  carts.id,
  carts.status,
  carts.created_at,
  carts.updated_at,
 COALESCE(json_agg(json_build_object(
    'id', cart_items.id,
    'cart_id', cart_items.cart_id,
    'product_id', cart_items.product_id,
    'quantity', cart_items.quantity,
    'created_at', cart_items.created_at
  ) ORDER BY cart_items.created_at) FILTER (WHERE cart_items.id IS NOT NULL), '[]')::json AS items
FROM carts
LEFT JOIN cart_items ON carts.id = cart_items.cart_id
WHERE cart_id = $1::text
GROUP BY carts.id
LIMIT 1
`

type GetCartByIdWithItemsRow struct {
	ID        string
	Status    CartStatus
	CreatedAt time.Time
	UpdatedAt time.Time
	Items     []byte
}

func (q *Queries) GetCartByIdWithItems(ctx context.Context, cartID string) (GetCartByIdWithItemsRow, error) {
	row := q.db.QueryRow(ctx, getCartByIdWithItems, cartID)
	var i GetCartByIdWithItemsRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Items,
	)
	return i, err
}

const listCarts = `-- name: ListCarts :many
SELECT
  id,
  status,
  created_at,
  updated_at
FROM carts
ORDER BY created_at
`

func (q *Queries) ListCarts(ctx context.Context) ([]Cart, error) {
	rows, err := q.db.Query(ctx, listCarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cart
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartStatus = `-- name: UpdateCartStatus :exec
UPDATE carts
  set status = $1::text,
  updated_at = $2::timestamptz
WHERE id = $3::text
`

type UpdateCartStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateCartStatus(ctx context.Context, arg UpdateCartStatusParams) error {
	_, err := q.db.Exec(ctx, updateCartStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
