// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
  id, name, description, price, discount, created_at, updated_at
) VALUES (
  $1::text, $2::text, $3::text, $4::int, $5::int, $6::timestamptz, $7::timestamptz
)
`

type CreateProductParams struct {
	ID          string
	Name        string
	Description string
	Price       int
	Discount    int
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Discount,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProductById = `-- name: DeleteProductById :exec
DELETE FROM products
WHERE id = $1::text
`

func (q *Queries) DeleteProductById(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProductById, id)
	return err
}

const getProductById = `-- name: GetProductById :one
SELECT
  id, 
  name,
  description,
  image,
  price,
  discount,
  created_at,
  updated_at
FROM products
WHERE id = $1::text LIMIT 1
`

func (q *Queries) GetProductById(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Price,
		&i.Discount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByName = `-- name: GetProductByName :one
SELECT
  id, 
  name,
  description,
  image,
  price,
  discount,
  created_at,
  updated_at
FROM products
WHERE name = $1::text LIMIT 1
`

func (q *Queries) GetProductByName(ctx context.Context, name string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByName, name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.Price,
		&i.Discount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
  id, 
  name,
  description,
  price,
  discount,
  created_at,
  updated_at
FROM products
ORDER BY created_at
`

type ListProductsRow struct {
	ID          string
	Name        string
	Description pgtype.Text
	Price       int
	Discount    pgtype.Int4
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Discount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
  set name = $1::text,
  description = $2::text,
  price = $3::int,
  discount = $4::int,
  updated_at = $5::timestamptz
WHERE id = $6::text
`

type UpdateProductParams struct {
	Name        string
	Description string
	Price       int
	Discount    int
	UpdatedAt   time.Time
	ID          string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Discount,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProductImage = `-- name: UpdateProductImage :exec
UPDATE products
  set image = $1::text,
  updated_at = $2::timestamptz
WHERE id = $3::text
`

type UpdateProductImageParams struct {
	Image     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error {
	_, err := q.db.Exec(ctx, updateProductImage, arg.Image, arg.UpdatedAt, arg.ID)
	return err
}
